export const PRO_FEATURES = [
  {
    feature: "Faster processing",
  },
  {
    feature: "Unlimited AI Usage",
  },
  {
    feature: "No ads forever",
  },
];

export const SAMPLE_PROMPT_FOR_CREATE_FUNNY_EMOJI = [
  "Create a laughing emoji with tears rolling down, but make it wear a clown hat.",
  "Design an angry emoji with steam coming out of its ears and a tiny tornado on top of its head.",
  "Make a sleepy emoji with a snoring bubble, but add a blanket wrapped around its face.",
  "Create a confused emoji with swirly eyes and a question mark floating above its head.",
  "Design a happy emoji with sunglasses and a beach ball in its hand.",
  "Make a shocked emoji with its mouth open and its face shaped like a star.",
  "Create a crying emoji with a comically oversized waterfall of tears.",
  "Design a smug emoji with a sideways grin and an eyebrow raised like The Rock.",
  "Make a winking emoji holding a cheeky sign that says 'Oops!'",
  "Create a silly emoji with its tongue out, eyes crossed, and a party hat.",
  "Design a scared emoji with trembling cheeks and a ghost hovering over its head.",
  "Make an emoji eating popcorn with wide eyes, like it's watching a drama unfold.",
  "Create a dancing emoji with jazz hands and a disco ball in the background.",
  "Design a thinking emoji with a hand on its chin and a light bulb over its head.",
  "Make a facepalm emoji with exaggerated hands and a comically shocked expression.",
  "Create a sneezing emoji with a giant tissue and tiny sneezing clouds.",
  "Design a laughing emoji holding its stomach, as if it's laughing too hard to stand.",
  "Make a sleepy emoji falling asleep mid-yawn, with a tiny moon hovering above.",
  "Create an emoji with sunglasses and a mustache, pretending to be a detective.",
  "Design a crying emoji with buckets under its eyes collecting the tears.",
  "Make a party emoji with confetti exploding out of its head like a volcano.",
  "Create an emoji riding a tiny scooter with wind lines behind it.",
  "Design a nerdy emoji with oversized glasses and a book sticking out of its head.",
  "Make a shocked emoji with its hair standing straight up as if electrified.",
  "Create a sneaky emoji peeking out from behind a tree or a wall.",
  "Design an emoji with its tongue sticking out and an ice cream cone in hand.",
  "Make an emoji blowing a bubble with gum, the bubble covering half its face.",
  "Create a cool emoji with headphones and a tiny DJ turntable in front of it.",
  "Design a dizzy emoji with stars spinning around its head and a wobbly expression.",
  "Make an emoji wearing a superhero cape, striking a heroic pose.",
  "Create a panicking emoji holding a sign that says 'HELP!'",
  "Design an emoji turning into a robot with gears and circuits visible.",
  "Make a suspicious emoji looking sideways with a monocle over one eye.",
  "Create a hungry emoji with a fork and knife, staring at a giant burger.",
  "Design a grumpy emoji sitting in a tiny raincloud, holding an umbrella.",
];
